sudo: false
dist: trusty
language: node_js
node_js:
  - 10
cache:
  directories:
    - node_modules
branches:
  only:
    - master
script:
  - yarn test --coverage
  - yarn build
after_script:
  - COVERALLS_REPO_TOKEN=$coveralls_repo_token yarn report-coverage
