sudo: false
dist: trusty
language: node_js
node_js:
  - 10.15.3
branches:
  only:
    - master
script:
  - npm run test -- --coverage --watchAll=false
  - npm run build
after_script:
  - COVERALLS_REPO_TOKEN=$coveralls_repo_token coveralls < ./coverage/lcov.info
